# Generated by Django 3.2.23 on 2023-12-27 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('target', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('unisex', 'unisex')], max_length=15, null=True)),
                ('image', models.ImageField(default='default_perfume.png', upload_to='perfume_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Perfume_Fragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('oz', 'ounce'), ('ml', 'mililitre'), ('l', 'litre'), ('g', 'gram')], max_length=15, null=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.fragrance')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.perfume')),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='fragrances',
            field=models.ManyToManyField(through='perfume.Perfume_Fragrance', to='perfume.Fragrance'),
        ),
    ]
